name : pokemon api project

on : 
  push :
    branches : [ main ] 

jobs :
  build-app :
    runs-on : ubuntu-latest 

    steps : 
      - uses: actions/checkout@v6.0.1
      
      - name : Install Dependencies 
        run : npm install
     
      - name : build react app 
        run  : npm run build

      - name : upload Build on Artifacts 
        uses: actions/upload-artifact@v6.0.0
        with :
          name : pokemon-api
          path : out/

          
        
