name : pokemon api project

on : 
  push :
    branches : [ main ] 

jobs :
  build-app :
    runs-on : ubuntu-latest 

    steps : 
      - uses: actions/checkout@v6.0.1
      - name : Install Dependencies 
        run : npm install
      - name : build react app 
        run  : npm run build

        
